spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    username: postgres
    password: password

  jpa:
    show-sql: true

app:
    base-url: http://localhost:8080

logging:
  level:
    com.notso: DEBUG