services:
  # Traefik reverse proxy
  traefik:
    image: traefik:v3.0
    container_name: tinyurl-traefik
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      #Redirect HTTP to HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      #Encrypt
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt_data:/letsencrypt
    networks:
      - tinyurl-network
    restart: unless-stopped
    # TinyURL application service
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: tinyurl-app
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE:-local}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tinyurl
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      BASE_URL: ${BASE_URL:-http://localhost:8080}
      SERVER_PORT: 8080
    labels:
      - "traefik.enable=true"
      # Http Resolver
      - "traefik.http.routers.tinyurl.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.tinyurl.entrypoints=websecure"
      - "traefik.http.routers.tinyurl.tls.certresolver=letsencrypt"
      # Service
      - "traefik.http.services.tinyurl.loadbalancer.server.port=8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD","wget","--no-verbose","--tries=1","--spider","http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - tinyurl-network
    restart: unless-stopped

    # Database service using PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: tinyurl-postgres
    environment:
      POSTGRES_DB: tinyurl
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d tinyurl" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tinyurl-network
    restart: unless-stopped

    #Do not expose port in prod
volumes:
  postgres_data:
  letsencrypt_data:

networks:
  tinyurl-network:
    driver: bridge